name: Deploy API Gateway

on:
  push:
    branches:
      - main

jobs:
  deploy:
    uses: edwinmalihu/jenkins-script/.github/workflows/reusable-flyio-deploy.yml@main
    with:
      # Berikan nama aplikasi yang sesuai
      app-name: "customer-service-git"
      # Berikan nama file .toml yang spesifik untuk layanan ini
      config-file: "api-gateway.toml"
    secrets:
      FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
      # PAT_TOKEN: ${{ secrets.YOUR_PAT_TOKEN }} # Jika perlu
